services:
  - type: web
    name: mern-crud-auth-backend
    env: node
    plan: free
    buildCommand: npm install --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3003
      - key: MONGODB_URI
        fromDatabase:
          name: mern-crud-auth-db
          property: connectionString
      - key: TOKEN_SECRET
        generateValue: true
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: mern-crud-auth-db
    plan: free